-- ===========================================================================
-- AgendaSalud — Esquema Supabase (rama dev, modelo "persona")
-- Deducido del código: controllers + frontend de la rama dev.
-- ---------------------------------------------------------------------------
-- MODELO CENTRAL: una tabla `persona` con los datos comunes (dni, nombre,
-- apellido, etc.) y su vínculo a auth.users (id_auth). `paciente` y
-- `profesional` son "roles" que cuelgan de persona vía id_persona.
--
-- CÓMO USAR:
--   - SECCIÓN A: tablas que YA existen en tu Supabase. Están con IF NOT EXISTS
--     para que las VERIFIQUES sin pisarlas. Si algún tipo/columna difiere,
--     gana el de tu base y avisá para ajustar el código.
--   - SECCIÓN B: tablas NUEVAS de historia clínica (Fase 1). Estas hay que crearlas.
--   - SECCIÓN C: multi-clínica (Fase 2). NO ejecutar todavía.
--
-- OJO con los tipos de id: el código usa persona.id / paciente.id / profesional.id
-- como enteros de identidad. Verificá que en tu base sean bigint identity (no uuid).
-- ===========================================================================


-- ===========================================================================
-- SECCIÓN A — TABLAS EXISTENTES (verificar contra tu base, no recrear a ciegas)
-- ===========================================================================

-- Datos comunes de toda persona (paciente o profesional).
CREATE TABLE IF NOT EXISTS persona (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_auth          uuid UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
    dni              text UNIQUE NOT NULL,
    nombre           text NOT NULL,
    apellido         text,
    fecha_nacimiento date,
    telefono         text,
    direccion        text,
    sexo             text
);

-- Rol paciente.
CREATE TABLE IF NOT EXISTS paciente (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona  bigint UNIQUE REFERENCES persona(id) ON DELETE CASCADE,
    obra_social text
);

-- Rol profesional.
CREATE TABLE IF NOT EXISTS profesional (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona    bigint UNIQUE REFERENCES persona(id) ON DELETE CASCADE,
    telefono      text,
    direccion     text,
    matricula     text,
    id_calendario text,          -- ID del Google Calendar del profesional
    descripcion   text,
    precio        text
);

-- Catálogo de especialidades/áreas.
CREATE TABLE IF NOT EXISTS especialidad (
    id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text UNIQUE NOT NULL
);

-- Relación N:M profesional <-> especialidad.
CREATE TABLE IF NOT EXISTS especialidad_profesional (
    id_profesional  bigint REFERENCES profesional(id)  ON DELETE CASCADE,
    id_especialidad bigint REFERENCES especialidad(id) ON DELETE CASCADE,
    PRIMARY KEY (id_profesional, id_especialidad)
);

-- Horarios de atención del profesional.
CREATE TABLE IF NOT EXISTS horario_profesional (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profesional bigint REFERENCES profesional(id) ON DELETE CASCADE,
    dia            text NOT NULL,           -- ej: 'Lunes'
    horario_inicio text NOT NULL,           -- ej: '09:00'
    horario_fin    text NOT NULL            -- ej: '18:00'
);

-- Valor de ortodoncia por paciente.
-- El controller consulta: paciente(persona(dni,...)) filtrando por persona.dni.
CREATE TABLE IF NOT EXISTS pacientes_ortodoncia (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente bigint REFERENCES paciente(id) ON DELETE CASCADE,
    valor       numeric NOT NULL,
    aumento     numeric NOT NULL DEFAULT 0    -- porcentaje de aumento mensual
);


-- ===========================================================================
-- SECCIÓN B — TABLAS NUEVAS: HISTORIA CLÍNICA (Fase 1) — EJECUTAR
-- ---------------------------------------------------------------------------
-- Historia clínica: un registro por consulta; el odontograma se guarda por consulta.
-- ===========================================================================

-- Email de contacto de la persona (aditivo). Los pacientes cargados desde la
-- historia clínica no son usuarios de auth, así que su email se guarda acá.
ALTER TABLE persona ADD COLUMN IF NOT EXISTS email text;

CREATE TABLE IF NOT EXISTS registro_clinico (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    id_paciente        bigint NOT NULL REFERENCES paciente(id) ON DELETE CASCADE,
    id_profesional     bigint REFERENCES profesional(id) ON DELETE SET NULL,
    profesional_nombre text,                 -- snapshot del nombre del profesional
    area               text,                 -- snapshot de la especialidad
    fecha              timestamptz NOT NULL DEFAULT now(),
    sintomas           text,
    diagnostico        text,
    tratamiento        text,
    creado_en          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_registro_clinico_paciente ON registro_clinico (id_paciente);
CREATE INDEX IF NOT EXISTS idx_registro_clinico_fecha    ON registro_clinico (fecha DESC);

-- Estado del odontograma, por registro clínico (uno por diente).
-- 'numero' coincide con el id del elemento <svg> del odontograma del frontend.
CREATE TABLE IF NOT EXISTS registro_diente (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    id_registro  uuid NOT NULL REFERENCES registro_clinico(id) ON DELETE CASCADE,
    numero       text NOT NULL,
    estado       text NOT NULL DEFAULT 'sano'
                 CHECK (estado IN ('sano','caries','tratado','falta')),
    notas        text
);

CREATE INDEX IF NOT EXISTS idx_registro_diente_registro ON registro_diente (id_registro);

-- RLS: activar para cerrar por defecto (el backend usa service_role y la salta).
ALTER TABLE registro_clinico ENABLE ROW LEVEL SECURITY;
ALTER TABLE registro_diente  ENABLE ROW LEVEL SECURITY;


-- ===========================================================================
-- SECCIÓN C — MULTI-CLÍNICA (Fase 2) — NO EJECUTAR TODAVÍA (referencia)
-- ---------------------------------------------------------------------------
-- Para vender el mismo sistema a varias clínicas con datos aislados:
--   1. Crear tabla clinica.
--   2. Agregar clinica_id a: persona, profesional, registro_clinico, etc.
--   3. Definir RLS por clinica_id (cada usuario solo ve datos de su clínica).
-- ===========================================================================
-- CREATE TABLE clinica (
--     id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--     nombre     text NOT NULL,
--     plan       text NOT NULL DEFAULT 'free',
--     activa     boolean NOT NULL DEFAULT true,
--     creada_en  timestamptz NOT NULL DEFAULT now()
-- );
-- ALTER TABLE persona          ADD COLUMN clinica_id uuid REFERENCES clinica(id);
-- ALTER TABLE profesional      ADD COLUMN clinica_id uuid REFERENCES clinica(id);
-- ALTER TABLE registro_clinico ADD COLUMN clinica_id uuid REFERENCES clinica(id);
-- ... + policies RLS por clinica_id.
