-- ===========================================================================
-- AgendaSalud — Fase M: cobro de la suscripción de las clínicas con Mercado Pago
-- ---------------------------------------------------------------------------
-- Ejecutar UNA vez en el SQL Editor de Supabase, DESPUÉS de faseL_planes.sql.
-- Es IDEMPOTENTE.
--
-- Modelo (Suscripciones de Mercado Pago "sin plan asociado", con pago pendiente):
--   * El admin elige plan/ciclo/profesionales extra → se crea un `preapproval` en MP
--     y se guarda en `suscripcion_checkout` (qué se eligió y quién). El admin paga en
--     el checkout de MP (init_point) y queda el débito automático.
--   * Cuando MP autoriza el preapproval, se aplica a `suscripcion` (plan, ciclo,
--     extras, monto) y se cancela el preapproval anterior si lo había.
--   * Cada cobro (authorized_payment) se registra en `suscripcion_pago`. Un cobro
--     APROBADO extiende el período pago: desde el mayor entre la fecha del cobro, el
--     fin del último período pago y el fin de la prueba; hasta + 1 o 12 meses.
--   * Idempotente: un cobro se identifica por su id de MP (UNIQUE) y su período se
--     asigna una sola vez.
--
-- Solo cobra a la CLÍNICA. El paciente no paga nada a la plataforma.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS suscripcion_pago; DROP TABLE IF EXISTS suscripcion_checkout;
--   ALTER TABLE suscripcion DROP COLUMN IF EXISTS mp_preapproval_id, DROP COLUMN IF EXISTS mp_estado,
--     DROP COLUMN IF EXISTS mp_payer_email, DROP COLUMN IF EXISTS monto,
--     DROP COLUMN IF EXISTS renovacion_automatica, DROP COLUMN IF EXISTS proximo_cobro;
-- ===========================================================================

-- 1. Datos del débito automático vigente en la suscripción.
ALTER TABLE suscripcion
    ADD COLUMN IF NOT EXISTS mp_preapproval_id     text,
    ADD COLUMN IF NOT EXISTS mp_estado             text,        -- espejo de MP: pending | authorized | paused | cancelled
    ADD COLUMN IF NOT EXISTS mp_payer_email        text,
    ADD COLUMN IF NOT EXISTS monto                 numeric(12,2), -- lo que se cobra por ciclo
    ADD COLUMN IF NOT EXISTS renovacion_automatica boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS proximo_cobro         timestamptz;

-- 2. Intentos de contratación (un preapproval de MP por intento).
CREATE TABLE IF NOT EXISTS suscripcion_checkout (
    mp_preapproval_id   text PRIMARY KEY,
    clinica_id          uuid NOT NULL REFERENCES clinica(id) ON DELETE CASCADE,
    plan_id             text NOT NULL REFERENCES plan(id),
    ciclo               text NOT NULL CHECK (ciclo IN ('mensual', 'anual')),
    profesionales_extra int  NOT NULL DEFAULT 0 CHECK (profesionales_extra >= 0),
    monto               numeric(12,2) NOT NULL CHECK (monto > 0),
    payer_email         text NOT NULL,
    init_point          text,
    estado              text NOT NULL DEFAULT 'pending',      -- espejo del preapproval en MP
    creado_por          bigint REFERENCES persona(id) ON DELETE SET NULL,
    creado_en           timestamptz NOT NULL DEFAULT now(),
    actualizado_en      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_suscripcion_checkout_clinica ON suscripcion_checkout (clinica_id, creado_en DESC);

-- 3. Cobros de la suscripción (facturas de MP: authorized_payments).
CREATE TABLE IF NOT EXISTS suscripcion_pago (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinica_id               uuid NOT NULL REFERENCES clinica(id) ON DELETE CASCADE,
    mp_authorized_payment_id text NOT NULL UNIQUE,
    mp_payment_id            text,
    mp_preapproval_id        text NOT NULL,
    monto                    numeric(12,2),
    estado                   text NOT NULL,                    -- estado del pago en MP (approved, rejected, ...)
    fecha                    timestamptz NOT NULL,
    plan_id                  text REFERENCES plan(id),
    ciclo                    text CHECK (ciclo IN ('mensual', 'anual')),
    -- Período que cubre (solo los aprobados; se asigna una vez).
    periodo_desde            timestamptz,
    periodo_hasta            timestamptz,
    creado_en                timestamptz NOT NULL DEFAULT now(),
    actualizado_en           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_suscripcion_pago_clinica ON suscripcion_pago (clinica_id, fecha DESC);

-- 4. RLS: solo el backend (service_role) lee y escribe estas tablas.
--    Sin políticas = denegado para anon/authenticated.
ALTER TABLE suscripcion_checkout ENABLE ROW LEVEL SECURITY;
ALTER TABLE suscripcion_pago     ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON suscripcion_checkout, suscripcion_pago FROM anon, authenticated;
