-- ===========================================================================
-- AgendaSalud — Fase 3: tabla `turno` (fuente de verdad del vínculo paciente↔turno)
-- ---------------------------------------------------------------------------
-- Ejecutar UNA vez en el SQL Editor de Supabase, DESPUÉS de fase2c_rls_jwt.sql.
-- Es idempotente.
--
-- Motivación: hasta ahora los turnos vivían SOLO en Google Calendar y el único
-- "vínculo" con la persona era el email escrito en la descripción del evento.
-- Eso hacía imposible mostrar "mis turnos" de forma segura (cualquiera podía
-- tipear un email ajeno y verlos → enumeración). A partir de esta fase:
--
--   * Google Calendar sigue siendo el MOTOR de disponibilidad y el evento real.
--   * `turno` (en Supabase) es la FUENTE DE VERDAD de quién es el dueño del turno.
--
-- Dos caminos de reserva:
--   a) Paciente logueado  -> el turno se ata a su paciente.id (id_paciente).
--   b) Invitado sin cuenta -> id_paciente NULL; se gestiona por un token único
--      (manage_token) que se le envía por email. Guardamos solo el HASH del token.
--
-- ROLLBACK: DROP TABLE IF EXISTS turno;  (borra todos los vínculos, no los eventos)
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Tabla turno
--    OJO con los tipos: profesional.id / paciente.id son bigint; clinica.id es uuid.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS turno (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profesional     bigint NOT NULL REFERENCES profesional(id) ON DELETE CASCADE,
    id_paciente        bigint REFERENCES paciente(id) ON DELETE SET NULL, -- NULL = invitado
    clinica_id         uuid   REFERENCES clinica(id) ON DELETE SET NULL,
    google_event_id    text,                       -- evento en el calendario del profesional
    google_calendar_id text,                       -- calendario donde vive el evento (para cancelar)
    -- Snapshot del profesional (evita joins cross-clínica que la RLS bloquearía al
    -- consultar "mis turnos" como paciente).
    profesional_nombre text,
    especialidad       text,
    -- Snapshot de contacto (invitados o histórico; el logueado igual queda con su id).
    paciente_nombre    text,
    paciente_email     text,
    paciente_telefono  text,
    -- Gestión por invitado: hash (sha256 hex) del token que viaja en el email.
    manage_token_hash  text,
    inicio             timestamptz NOT NULL,
    fin                timestamptz,
    estado             text NOT NULL DEFAULT 'reservado'
                       CHECK (estado IN ('reservado', 'cancelado')),
    creado_en          timestamptz NOT NULL DEFAULT now()
);

-- Índices para los accesos típicos.
CREATE INDEX IF NOT EXISTS idx_turno_paciente     ON turno (id_paciente);
CREATE INDEX IF NOT EXISTS idx_turno_profesional  ON turno (id_profesional);
CREATE INDEX IF NOT EXISTS idx_turno_clinica      ON turno (clinica_id);
CREATE INDEX IF NOT EXISTS idx_turno_event        ON turno (google_event_id);
CREATE INDEX IF NOT EXISTS idx_turno_token_hash   ON turno (manage_token_hash);

-- ---------------------------------------------------------------------------
-- 2. Helper: paciente.id del usuario autenticado (a partir del JWT auth.uid()).
--    SECURITY DEFINER + search_path fijo: lee salteando la RLS de persona/paciente
--    para no recursar dentro de la política de turno.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.app_current_paciente_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT pa.id
    FROM paciente pa
    JOIN persona pe ON pe.id = pa.id_persona
    WHERE pe.id_auth = auth.uid()
    LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION public.app_current_paciente_id() TO authenticated;

-- ---------------------------------------------------------------------------
-- 3. Privilegios de tabla para el rol authenticated (la RLS filtra las filas).
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON turno TO authenticated;

-- ---------------------------------------------------------------------------
-- 4. RLS
--    - El paciente logueado ve y cancela SOLO sus propios turnos (id_paciente).
--    - El profesional ve los turnos de SU clínica (para el panel).
--    - Los invitados (id_paciente NULL) NO son visibles vía RLS: se gestionan
--      exclusivamente desde el backend con service_role + manage_token.
--    - El alta la hace el backend (service_role, que saltea RLS) porque además
--      crea el evento en Google Calendar.
-- ---------------------------------------------------------------------------
ALTER TABLE turno ENABLE ROW LEVEL SECURITY;

-- Paciente dueño: lectura de sus turnos.
DROP POLICY IF EXISTS turno_paciente_select ON turno;
CREATE POLICY turno_paciente_select ON turno
    FOR SELECT TO authenticated
    USING (id_paciente = public.app_current_paciente_id());

-- Paciente dueño: cancelar (marcar estado). No puede cambiar de dueño.
DROP POLICY IF EXISTS turno_paciente_update ON turno;
CREATE POLICY turno_paciente_update ON turno
    FOR UPDATE TO authenticated
    USING (id_paciente = public.app_current_paciente_id())
    WITH CHECK (id_paciente = public.app_current_paciente_id());

-- Profesional: lectura de los turnos de su clínica (dashboard).
DROP POLICY IF EXISTS turno_clinica_select ON turno;
CREATE POLICY turno_clinica_select ON turno
    FOR SELECT TO authenticated
    USING (clinica_id = public.app_current_clinica_id());
