-- ===========================================================================
-- AgendaSalud — Fase C: Certificados médicos
-- ---------------------------------------------------------------------------
-- Ejecutar UNA vez en el SQL Editor de Supabase, DESPUÉS de faseA_membresia.sql.
-- Es IDEMPOTENTE.
--
-- Modelo:
--   * El profesional carga su FIRMA/SELLO (imagen) una vez -> profesional.firma_path.
--   * Emite un certificado de dos formas:
--       - 'generado': el backend arma un PDF (con la firma embebida) desde un formulario.
--       - 'subido'  : sube la foto/PDF de un certificado físico ya emitido.
--   * El PACIENTE descarga SUS certificados desde su panel.
--
-- Archivos en Storage (buckets PRIVADOS): la app los sube/baja por el backend
-- (service_role) y entrega URLs firmadas de corta duración. La tabla lleva la RLS
-- por clínica (profesional) y por paciente (dueño).
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS certificado_medico;
--   ALTER TABLE profesional DROP COLUMN IF EXISTS firma_path, DROP COLUMN IF EXISTS firma_mime;
--   DELETE FROM storage.buckets WHERE id IN ('firmas','certificados'); -- (borrar objetos antes)
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Firma/sello del profesional (path del objeto en el bucket 'firmas').
-- ---------------------------------------------------------------------------
ALTER TABLE profesional ADD COLUMN IF NOT EXISTS firma_path text;
ALTER TABLE profesional ADD COLUMN IF NOT EXISTS firma_mime text;

-- ---------------------------------------------------------------------------
-- 2. Tabla certificado_medico.
--    Tipos: profesional.id / paciente.id bigint; clinica.id uuid.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS certificado_medico (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinica_id         uuid   REFERENCES clinica(id) ON DELETE SET NULL,
    id_profesional     bigint REFERENCES profesional(id) ON DELETE SET NULL,
    id_paciente        bigint NOT NULL REFERENCES paciente(id) ON DELETE CASCADE,
    tipo               text   NOT NULL CHECK (tipo IN ('generado', 'subido')),
    archivo_path       text   NOT NULL,          -- objeto en el bucket 'certificados'
    archivo_mime       text,
    -- Datos del certificado 'generado' (snapshot).
    motivo             text,
    diagnostico        text,
    indicaciones       text,
    dias_reposo        int,
    -- Snapshots para mostrar/listar sin joins cross-clínica.
    paciente_nombre    text,
    profesional_nombre text,
    emitido_en         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_certificado_paciente    ON certificado_medico (id_paciente);
CREATE INDEX IF NOT EXISTS idx_certificado_clinica     ON certificado_medico (clinica_id);
CREATE INDEX IF NOT EXISTS idx_certificado_profesional ON certificado_medico (id_profesional);

-- ---------------------------------------------------------------------------
-- 3. RLS: profesional ve/crea los de su clínica activa; paciente ve los suyos.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT ON certificado_medico TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE certificado_medico_id_seq TO authenticated;

ALTER TABLE certificado_medico ENABLE ROW LEVEL SECURITY;

-- Lectura: el profesional de la clínica del certificado, o el paciente dueño.
DROP POLICY IF EXISTS certificado_select ON certificado_medico;
CREATE POLICY certificado_select ON certificado_medico
    FOR SELECT TO authenticated
    USING (
        clinica_id = public.app_current_clinica_id()
        OR id_paciente = public.app_current_paciente_id()
    );

-- Alta: solo dentro de la clínica activa (lo hace el profesional).
DROP POLICY IF EXISTS certificado_insert ON certificado_medico;
CREATE POLICY certificado_insert ON certificado_medico
    FOR INSERT TO authenticated
    WITH CHECK (clinica_id = public.app_current_clinica_id());

-- ---------------------------------------------------------------------------
-- 4. Buckets de Storage PRIVADOS. El acceso lo media el backend (service_role);
--    no se agregan políticas para anon/authenticated -> quedan cerrados al cliente.
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('firmas', 'firmas', false)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('certificados', 'certificados', false)
ON CONFLICT (id) DO NOTHING;
