-- ===========================================================================
-- AgendaSalud — Fase F: la tabla `turno` como ÚNICA fuente de disponibilidad
-- ---------------------------------------------------------------------------
-- Ejecutar UNA vez en el SQL Editor de Supabase. Es idempotente.
--
-- Se elimina la dependencia de Google Calendar: la disponibilidad de turnos se
-- calcula ahora como `horario_profesional` (días/horas que atiende) menos los
-- `turno` reservados menos los `bloqueo_horario` (ausencias). Esta migración
-- agrega lo que falta para eso:
--
--   1. `bloqueo_horario`: franjas que el staff bloquea (vacaciones, ausencias).
--   2. `turno.recordatorio_enviado`: los recordatorios de 24 h ya no leen el
--      calendario; recorren la tabla `turno` y marcan acá para no repetir.
--
-- NOTA: `profesional.id_calendario` y las columnas `google_*` de `turno` se
-- conservan (no se borran datos), pero dejan de usarse.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS bloqueo_horario;
--   ALTER TABLE turno DROP COLUMN IF EXISTS recordatorio_enviado;
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Bloqueos de horario (ausencias del profesional).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bloqueo_horario (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profesional bigint NOT NULL REFERENCES profesional(id) ON DELETE CASCADE,
    clinica_id     uuid   REFERENCES clinica(id) ON DELETE SET NULL,
    inicio         timestamptz NOT NULL,
    fin            timestamptz NOT NULL,
    motivo         text,
    creada_por     uuid,                       -- persona.id_auth que lo creó
    creada_en      timestamptz NOT NULL DEFAULT now(),
    CHECK (fin > inicio)
);

CREATE INDEX IF NOT EXISTS idx_bloqueo_profesional ON bloqueo_horario (id_profesional, inicio);
CREATE INDEX IF NOT EXISTS idx_bloqueo_clinica     ON bloqueo_horario (clinica_id);

-- ---------------------------------------------------------------------------
-- 2. Flag de recordatorio en el turno (reemplaza el extendedProperties de Google).
-- ---------------------------------------------------------------------------
ALTER TABLE turno
    ADD COLUMN IF NOT EXISTS recordatorio_enviado boolean NOT NULL DEFAULT false;

-- ---------------------------------------------------------------------------
-- 3. RLS de bloqueo_horario.
--    El acceso real es por el backend con service_role acotado por clínica (igual
--    que turnos/administración). La RLS queda como respaldo: solo miembros del
--    staff de la clínica (app_is_clinica_member) pueden ver/gestionar sus bloqueos.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON bloqueo_horario TO authenticated;
ALTER TABLE bloqueo_horario ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bloqueo_staff_all ON bloqueo_horario;
CREATE POLICY bloqueo_staff_all ON bloqueo_horario
    FOR ALL TO authenticated
    USING (clinica_id = public.app_current_clinica_id() AND public.app_is_clinica_member())
    WITH CHECK (clinica_id = public.app_current_clinica_id() AND public.app_is_clinica_member());
