-- ===========================================================================
-- AgendaSalud — Fase I: Mis estudios (repositorio del paciente + compartir)
-- ---------------------------------------------------------------------------
-- Ejecutar UNA vez en el SQL Editor de Supabase (o vía MCP), DESPUÉS de
-- fase3_turnos.sql y faseA_membresia.sql. Es IDEMPOTENTE.
--
-- Modelo ("Drive médico" del paciente):
--   * El PACIENTE sube sus estudios (labos, imágenes, informes) -> tabla `estudio`.
--     Es el DUEÑO del archivo.
--   * Comparte cada estudio con PROFESIONALES puntuales de la plataforma
--     (cross-clínica) -> tabla `estudio_compartido`. Revocar = borrar la fila.
--   * El PROFESIONAL destinatario los ve en su bandeja "Compartidos conmigo".
--
-- Archivos en Storage (bucket PRIVADO 'estudios'): la app los sube/baja por el
-- backend (service_role) y entrega URLs firmadas de corta duración. La tabla lleva
-- la RLS: dueño (paciente) para todo; profesional destinatario para lectura.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS estudio_compartido;
--   DROP TABLE IF EXISTS estudio;
--   DROP FUNCTION IF EXISTS public.app_current_profesional_id();
--   DELETE FROM storage.buckets WHERE id = 'estudios'; -- (borrar objetos antes)
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Helper: profesional.id del usuario autenticado (espeja app_current_paciente_id).
--    SECURITY DEFINER + search_path fijo: lee salteando la RLS de persona/profesional
--    para no recursar dentro de las políticas de estudio/estudio_compartido.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.app_current_profesional_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT pr.id
    FROM profesional pr
    JOIN persona pe ON pe.id = pr.id_persona
    WHERE pe.id_auth = auth.uid()
    LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION public.app_current_profesional_id() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.app_current_profesional_id() FROM anon, public;

-- ---------------------------------------------------------------------------
-- 1.b Helpers de acceso cruzado estudio <-> estudio_compartido.
--     SECURITY DEFINER (corren como el dueño de las tablas) => NO disparan la RLS
--     de la otra tabla. Sin esto las políticas se referencian mutuamente y Postgres
--     lanza "infinite recursion detected in policy".
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.app_estudio_es_mio(p_id_estudio bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1 FROM estudio e
        WHERE e.id = p_id_estudio
          AND e.id_paciente = public.app_current_paciente_id()
    );
$$;

CREATE OR REPLACE FUNCTION public.app_estudio_compartido_conmigo(p_id_estudio bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1 FROM estudio_compartido ec
        WHERE ec.id_estudio = p_id_estudio
          AND ec.id_profesional = public.app_current_profesional_id()
    );
$$;

GRANT EXECUTE ON FUNCTION public.app_estudio_es_mio(bigint)            TO authenticated;
GRANT EXECUTE ON FUNCTION public.app_estudio_compartido_conmigo(bigint) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.app_estudio_es_mio(bigint)            FROM anon, public;
REVOKE EXECUTE ON FUNCTION public.app_estudio_compartido_conmigo(bigint) FROM anon, public;

-- ---------------------------------------------------------------------------
-- 2. Tabla estudio (dueño = paciente).
--    Tipos: paciente.id bigint.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS estudio (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente    bigint NOT NULL REFERENCES paciente(id) ON DELETE CASCADE,
    titulo         text   NOT NULL,
    descripcion    text,
    categoria      text   NOT NULL DEFAULT 'otro'
                          CHECK (categoria IN ('laboratorio', 'imagen', 'informe', 'receta', 'otro')),
    fecha_estudio  date,                              -- fecha del estudio (opcional)
    archivo_path   text   NOT NULL,                   -- objeto en el bucket 'estudios'
    archivo_mime   text,
    archivo_nombre text,                              -- nombre original del archivo
    archivo_size   bigint,
    paciente_nombre text,                             -- snapshot para la bandeja del profesional
    subido_en      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_estudio_paciente ON estudio (id_paciente);
-- Idempotencia si la tabla ya existía sin la columna de snapshot.
ALTER TABLE estudio ADD COLUMN IF NOT EXISTS paciente_nombre text;

-- ---------------------------------------------------------------------------
-- 3. Tabla estudio_compartido (un estudio -> un profesional destinatario).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS estudio_compartido (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudio     bigint NOT NULL REFERENCES estudio(id)     ON DELETE CASCADE,
    id_profesional bigint NOT NULL REFERENCES profesional(id) ON DELETE CASCADE,
    profesional_nombre text,                          -- snapshot para la vista del paciente
    compartido_en  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id_estudio, id_profesional)
);
CREATE INDEX IF NOT EXISTS idx_estudio_compartido_estudio     ON estudio_compartido (id_estudio);
CREATE INDEX IF NOT EXISTS idx_estudio_compartido_profesional ON estudio_compartido (id_profesional);
-- Idempotencia si la tabla ya existía sin la columna de snapshot.
ALTER TABLE estudio_compartido ADD COLUMN IF NOT EXISTS profesional_nombre text;

-- ---------------------------------------------------------------------------
-- 4. RLS.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON estudio            TO authenticated;
GRANT SELECT, INSERT, DELETE          ON estudio_compartido TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE estudio_id_seq             TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE estudio_compartido_id_seq  TO authenticated;

ALTER TABLE estudio            ENABLE ROW LEVEL SECURITY;
ALTER TABLE estudio_compartido ENABLE ROW LEVEL SECURITY;

-- --- estudio ---
-- Lectura: el paciente DUEÑO, o un profesional al que se lo compartieron.
DROP POLICY IF EXISTS estudio_select ON estudio;
CREATE POLICY estudio_select ON estudio
    FOR SELECT TO authenticated
    USING (
        id_paciente = public.app_current_paciente_id()
        OR public.app_estudio_compartido_conmigo(id)
    );

-- Alta / edición / borrado: solo el paciente dueño.
DROP POLICY IF EXISTS estudio_insert ON estudio;
CREATE POLICY estudio_insert ON estudio
    FOR INSERT TO authenticated
    WITH CHECK (id_paciente = public.app_current_paciente_id());

DROP POLICY IF EXISTS estudio_update ON estudio;
CREATE POLICY estudio_update ON estudio
    FOR UPDATE TO authenticated
    USING (id_paciente = public.app_current_paciente_id())
    WITH CHECK (id_paciente = public.app_current_paciente_id());

DROP POLICY IF EXISTS estudio_delete ON estudio;
CREATE POLICY estudio_delete ON estudio
    FOR DELETE TO authenticated
    USING (id_paciente = public.app_current_paciente_id());

-- --- estudio_compartido ---
-- Lectura: el paciente dueño del estudio, o el profesional destinatario.
DROP POLICY IF EXISTS estudio_compartido_select ON estudio_compartido;
CREATE POLICY estudio_compartido_select ON estudio_compartido
    FOR SELECT TO authenticated
    USING (
        id_profesional = public.app_current_profesional_id()
        OR public.app_estudio_es_mio(id_estudio)
    );

-- Compartir / revocar: solo el paciente dueño del estudio.
DROP POLICY IF EXISTS estudio_compartido_insert ON estudio_compartido;
CREATE POLICY estudio_compartido_insert ON estudio_compartido
    FOR INSERT TO authenticated
    WITH CHECK (public.app_estudio_es_mio(id_estudio));

DROP POLICY IF EXISTS estudio_compartido_delete ON estudio_compartido;
CREATE POLICY estudio_compartido_delete ON estudio_compartido
    FOR DELETE TO authenticated
    USING (public.app_estudio_es_mio(id_estudio));

-- ---------------------------------------------------------------------------
-- 5. Bucket de Storage PRIVADO. El acceso lo media el backend (service_role);
--    no se agregan políticas para anon/authenticated -> queda cerrado al cliente.
-- ---------------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('estudios', 'estudios', false)
ON CONFLICT (id) DO NOTHING;
