-- ===========================================================================
-- AgendaSalud — Fase A: Membresía y roles por clínica (multi-clínica real)
-- ---------------------------------------------------------------------------
-- Ejecutar UNA vez en el SQL Editor de Supabase, DESPUÉS de fase3_turnos.sql.
-- Es IDEMPOTENTE.
--
-- Motivación: hasta ahora "una persona = una clínica" (persona.clinica_id 1:1) y
-- el admin era un booleano (profesional.es_admin). A partir de esta fase un mismo
-- profesional puede pertenecer a VARIAS clínicas con un ROL DISTINTO en cada una.
--
--   * `membresia` = fuente de verdad de "quién pertenece a qué clínica y con qué rol".
--   * `persona`   = identidad global del profesional (1 por id_auth). persona.clinica_id
--                   queda como legacy (clínica de origen) y se conserva por compatibilidad.
--   * La "clínica activa" de la sesión viaja como header `x-clinica-id` (lo pone el backend
--     al operar por-JWT). app_current_clinica_id() la valida contra una membresía activa.
--
-- ROLLBACK (revierte función y borra membresías; NO borra personas/profesionales):
--   -- Restaurar la función anterior:
--   CREATE OR REPLACE FUNCTION public.app_current_clinica_id() RETURNS uuid
--   LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
--     SELECT clinica_id FROM persona WHERE id_auth = auth.uid() LIMIT 1; $$;
--   DROP TABLE IF EXISTS membresia;
--   DROP FUNCTION IF EXISTS public.app_is_clinica_admin();
--   -- (Las políticas de la sección 3b son ADITIVAS —solo agregan acceso a la
--   --  identidad propia—; para revertirlas exactamente, re-aplicar fase2c_rls_jwt.sql.)
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. Tabla membresia (id_persona bigint, clinica_id uuid).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS membresia (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona bigint NOT NULL REFERENCES persona(id) ON DELETE CASCADE,
    clinica_id uuid   NOT NULL REFERENCES clinica(id) ON DELETE CASCADE,
    rol        text   NOT NULL DEFAULT 'profesional'
                      CHECK (rol IN ('admin', 'profesional', 'recepcion')),
    activo     boolean NOT NULL DEFAULT true,
    creada_en  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id_persona, clinica_id)
);
CREATE INDEX IF NOT EXISTS idx_membresia_persona ON membresia (id_persona);
CREATE INDEX IF NOT EXISTS idx_membresia_clinica ON membresia (clinica_id);

-- ---------------------------------------------------------------------------
-- 2. Backfill: una membresía por cada profesional existente, según su clínica
--    de origen (persona.clinica_id) y su flag es_admin.
-- ---------------------------------------------------------------------------
INSERT INTO membresia (id_persona, clinica_id, rol, activo)
SELECT pr.id_persona,
       pe.clinica_id,
       CASE WHEN pr.es_admin THEN 'admin' ELSE 'profesional' END,
       true
FROM profesional pr
JOIN persona pe ON pe.id = pr.id_persona
WHERE pe.clinica_id IS NOT NULL
ON CONFLICT (id_persona, clinica_id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 3. Redefinir app_current_clinica_id(): "clínica activa" de la sesión.
--    - Sin membresías (PACIENTE / cuentas legacy): la clínica de la persona
--      (persona.clinica_id). Esto preserva el acceso del paciente a SUS datos,
--      que antes también dependía de esta función; el header se ignora.
--    - Con ≥1 membresía (profesional/admin/recepción):
--        * viene header x-clinica-id -> se devuelve SOLO si tiene membresía
--          ACTIVA en esa clínica (si no, NULL => la RLS niega).
--        * sin header y EXACTAMENTE una membresía -> esa (flujo mono-clínica).
--        * sin header y varias -> NULL (ambiguo => niega hasta elegir).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.app_current_clinica_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    WITH sel AS (
        SELECT NULLIF(
                 current_setting('request.headers', true)::json->>'x-clinica-id',
                 ''
               )::uuid AS cid
    ),
    mine AS (
        SELECT m.clinica_id
        FROM membresia m
        JOIN persona pe ON pe.id = m.id_persona
        WHERE pe.id_auth = auth.uid()
          AND m.activo = true
    )
    SELECT CASE
        WHEN (SELECT count(*) FROM mine) = 0 THEN
            -- Paciente / legacy sin membresías: su clínica de origen (ignora el header).
            (SELECT clinica_id FROM persona WHERE id_auth = auth.uid() LIMIT 1)
        WHEN (SELECT cid FROM sel) IS NOT NULL THEN
            (SELECT clinica_id FROM mine WHERE clinica_id = (SELECT cid FROM sel))
        WHEN (SELECT count(*) FROM mine) = 1 THEN
            (SELECT clinica_id FROM mine LIMIT 1)
        ELSE NULL
    END;
$$;

GRANT EXECUTE ON FUNCTION public.app_current_clinica_id() TO authenticated;
-- Solo authenticated la necesita (mismo criterio que fase2d).
REVOKE EXECUTE ON FUNCTION public.app_current_clinica_id() FROM anon, public;

-- ---------------------------------------------------------------------------
-- 3b. Excepción de IDENTIDAD PROPIA en las políticas de fase2c.
--     La persona/profesional del usuario tiene clinica_id = su clínica de ORIGEN.
--     Si trabaja en OTRA clínica (seleccionada), sin esta excepción la RLS le
--     bloquearía leer/editar su PROPIO perfil. Se agrega `OR id_auth = auth.uid()`
--     (identidad propia, independiente de la clínica activa). Idempotente.
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS persona_tenant ON persona;
CREATE POLICY persona_tenant ON persona
    FOR ALL TO authenticated
    USING (clinica_id = public.app_current_clinica_id() OR id_auth = auth.uid())
    WITH CHECK (clinica_id = public.app_current_clinica_id() OR id_auth = auth.uid());

DROP POLICY IF EXISTS profesional_tenant ON profesional;
CREATE POLICY profesional_tenant ON profesional
    FOR ALL TO authenticated
    USING (id_persona IN (
        SELECT id FROM persona
        WHERE clinica_id = public.app_current_clinica_id() OR id_auth = auth.uid()))
    WITH CHECK (id_persona IN (
        SELECT id FROM persona
        WHERE clinica_id = public.app_current_clinica_id() OR id_auth = auth.uid()));

DROP POLICY IF EXISTS especialidad_profesional_tenant ON especialidad_profesional;
CREATE POLICY especialidad_profesional_tenant ON especialidad_profesional
    FOR ALL TO authenticated
    USING (id_profesional IN (
        SELECT pr.id FROM profesional pr
        JOIN persona p ON p.id = pr.id_persona
        WHERE p.clinica_id = public.app_current_clinica_id() OR p.id_auth = auth.uid()))
    WITH CHECK (id_profesional IN (
        SELECT pr.id FROM profesional pr
        JOIN persona p ON p.id = pr.id_persona
        WHERE p.clinica_id = public.app_current_clinica_id() OR p.id_auth = auth.uid()));

-- ---------------------------------------------------------------------------
-- 4. Helper: ¿el usuario autenticado es admin de la clínica activa?
--    Se usa en las políticas de escritura (panel de administración, Fase B).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.app_is_clinica_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM membresia m
        JOIN persona pe ON pe.id = m.id_persona
        WHERE pe.id_auth = auth.uid()
          AND m.activo = true
          AND m.rol = 'admin'
          AND m.clinica_id = public.app_current_clinica_id()
    );
$$;

GRANT EXECUTE ON FUNCTION public.app_is_clinica_admin() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.app_is_clinica_admin() FROM anon, public;

-- Helper: ¿el usuario es MIEMBRO del staff (membresía activa) de la clínica activa?
-- Necesario para distinguir staff de pacientes en las políticas "por clínica": los
-- pacientes obtienen su clínica por el FALLBACK de app_current_clinica_id(), así que
-- una condición `clinica_id = app_current_clinica_id()` sola también daría verdadero
-- para ellos. Con este helper, la rama "por clínica" aplica solo al staff.
CREATE OR REPLACE FUNCTION public.app_is_clinica_member()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM membresia m
        JOIN persona pe ON pe.id = m.id_persona
        WHERE pe.id_auth = auth.uid()
          AND m.activo = true
          AND m.clinica_id = public.app_current_clinica_id()
    );
$$;
GRANT EXECUTE ON FUNCTION public.app_is_clinica_member() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.app_is_clinica_member() FROM anon, public;

-- ---------------------------------------------------------------------------
-- 5. RLS de membresia.
--    - Lectura: cada usuario ve SUS propias membresías (para el selector) y, si
--      opera dentro de una clínica, las de esa clínica activa (panel admin).
--    - Escritura (INSERT/UPDATE/DELETE): solo el admin de la clínica activa.
--      (El backend además exige requireClinicaAdmin; esto es el respaldo en Postgres.)
--    NOTA: el alta en el registro y el backfill los hace el service_role (saltea RLS).
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON membresia TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE membresia_id_seq TO authenticated;

ALTER TABLE membresia ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS membresia_select ON membresia;
CREATE POLICY membresia_select ON membresia
    FOR SELECT TO authenticated
    USING (
        (public.app_is_clinica_member() AND clinica_id = public.app_current_clinica_id())
        OR id_persona IN (SELECT id FROM persona WHERE id_auth = auth.uid())
    );

DROP POLICY IF EXISTS membresia_admin_insert ON membresia;
CREATE POLICY membresia_admin_insert ON membresia
    FOR INSERT TO authenticated
    WITH CHECK (clinica_id = public.app_current_clinica_id() AND public.app_is_clinica_admin());

DROP POLICY IF EXISTS membresia_admin_update ON membresia;
CREATE POLICY membresia_admin_update ON membresia
    FOR UPDATE TO authenticated
    USING (clinica_id = public.app_current_clinica_id() AND public.app_is_clinica_admin())
    WITH CHECK (clinica_id = public.app_current_clinica_id() AND public.app_is_clinica_admin());

DROP POLICY IF EXISTS membresia_admin_delete ON membresia;
CREATE POLICY membresia_admin_delete ON membresia
    FOR DELETE TO authenticated
    USING (clinica_id = public.app_current_clinica_id() AND public.app_is_clinica_admin());

-- ---------------------------------------------------------------------------
-- 6. Códigos de activación: permitir al admin ELIMINAR los NO usados.
--    (fase2c2 ya habilitó RLS + políticas de select/insert por clínica. Acá se
--     agrega la política de DELETE restringida a códigos libres de la clínica activa.)
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS codigo_activacion_admin_delete ON codigo_activacion;
CREATE POLICY codigo_activacion_admin_delete ON codigo_activacion
    FOR DELETE TO authenticated
    USING (
        clinica_id = public.app_current_clinica_id()
        AND public.app_is_clinica_admin()
        AND usado = false
    );
