-- ===========================================================================
-- AgendaSalud — Fase K: auditoría (tanda 2)
--   A. Obra social estructurada (catálogo + n.º de afiliado + plan).
--   B. Codificación: CIE-10 (subconjunto odontológico) y prácticas por clínica.
--   C. Autorizaciones previas de prácticas (con adjuntos).
--   D. Asistencia a turnos (atendido / ausente) y transparencia para el paciente.
-- ---------------------------------------------------------------------------
-- Ejecutar UNA vez en el SQL Editor de Supabase, DESPUÉS de faseJ_auditoria.sql.
-- Es IDEMPOTENTE.
--
-- Criterio de RLS (igual que la Fase J): las LECTURAS por-JWT las acota Postgres
-- (staff operativo de la clínica + auditor según su alcance); las ESCRITURAS de las
-- tablas nuevas las hace el backend con service_role, después de validar rol y alcance.
--
-- ROLLBACK (en orden):
--   DROP TABLE IF EXISTS autorizacion_adjunto, autorizacion, registro_practica,
--     registro_diagnostico, practica, cie10;
--   DROP TRIGGER IF EXISTS turno_asistencia_protegida ON turno;
--   DROP FUNCTION IF EXISTS public.turno_proteger_asistencia();
--   ALTER TABLE turno DROP CONSTRAINT turno_estado_check;
--   UPDATE turno SET estado = 'reservado' WHERE estado IN ('atendido','ausente');
--   ALTER TABLE turno ADD CONSTRAINT turno_estado_check CHECK (estado IN ('reservado','cancelado'));
--   ALTER TABLE membresia DROP COLUMN IF EXISTS alcance_id_obra_social;
--   ALTER TABLE codigo_activacion DROP COLUMN IF EXISTS alcance_id_obra_social;
--   ALTER TABLE paciente DROP COLUMN IF EXISTS id_obra_social, DROP COLUMN IF EXISTS nro_afiliado,
--     DROP COLUMN IF EXISTS plan;
--   DROP TABLE IF EXISTS obra_social;
--   Re-aplicar faseJ_auditoria.sql (funciones del auditor y políticas de hc_acceso).
--   DELETE FROM storage.buckets WHERE id = 'autorizaciones'; -- (borrar objetos antes)
-- ===========================================================================

-- ===========================================================================
-- A. OBRA SOCIAL ESTRUCTURADA
-- ===========================================================================

-- Catálogo. clinica_id NULL = global (lo ven todas las clínicas y los pacientes que
-- se registran solos, que no tienen clínica); con clinica_id = alta propia de la clínica.
CREATE TABLE IF NOT EXISTS obra_social (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinica_id uuid REFERENCES clinica(id) ON DELETE CASCADE,
    nombre     text NOT NULL,
    sigla      text,
    activo     boolean NOT NULL DEFAULT true,
    creado_en  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS obra_social_nombre_uq
    ON obra_social (COALESCE(clinica_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(nombre));
CREATE INDEX IF NOT EXISTS idx_obra_social_clinica ON obra_social (clinica_id);

-- Catálogo global base (las clínicas suman las suyas desde Administración).
INSERT INTO obra_social (clinica_id, nombre, sigla)
SELECT NULL, v.nombre, v.sigla
FROM (VALUES
    ('Particular', NULL),
    ('OSDE', NULL),
    ('Swiss Medical', NULL),
    ('Galeno', NULL),
    ('Medifé', NULL),
    ('Omint', NULL),
    ('Sancor Salud', NULL),
    ('Accord Salud', NULL),
    ('Avalian', NULL),
    ('Prevención Salud', NULL),
    ('Federada Salud', NULL),
    ('Jerárquicos Salud', NULL),
    ('Hospital Italiano - Plan de Salud', NULL),
    ('Hospital Alemán - Plan Médico', NULL),
    ('Hospital Británico - Plan de Salud', NULL),
    ('PAMI', 'INSSJP'),
    ('IOMA', NULL),
    ('IOSFA', NULL),
    ('OSECAC', NULL),
    ('OSPRERA', NULL),
    ('OSDEPYM', NULL),
    ('Unión Personal', NULL),
    ('OSPE', NULL),
    ('OSUTHGRA', NULL),
    ('OSPLAD', NULL)
) AS v(nombre, sigla)
WHERE NOT EXISTS (
    SELECT 1 FROM obra_social os WHERE os.clinica_id IS NULL AND lower(os.nombre) = lower(v.nombre)
);

-- Cobertura del paciente. `obra_social` (texto) se conserva como snapshot del nombre
-- (lo siguen mostrando la HC, el PDF y la auditoría); el backend lo mantiene en sync.
ALTER TABLE paciente ADD COLUMN IF NOT EXISTS id_obra_social bigint REFERENCES obra_social(id) ON DELETE SET NULL;
ALTER TABLE paciente ADD COLUMN IF NOT EXISTS nro_afiliado text;
ALTER TABLE paciente ADD COLUMN IF NOT EXISTS plan text;
CREATE INDEX IF NOT EXISTS idx_paciente_obra_social ON paciente (id_obra_social);

-- Backfill 1: textos que coinciden con el catálogo global (nombre o sigla).
UPDATE paciente pa
SET id_obra_social = os.id, obra_social = os.nombre
FROM obra_social os
WHERE pa.id_obra_social IS NULL
  AND os.clinica_id IS NULL
  AND pa.obra_social IS NOT NULL
  AND (lower(trim(pa.obra_social)) = lower(os.nombre) OR lower(trim(pa.obra_social)) = lower(os.sigla));

-- Backfill 2: el resto pasa a ser alta propia de la clínica del paciente.
INSERT INTO obra_social (clinica_id, nombre)
SELECT DISTINCT ON (pe.clinica_id, lower(trim(pa.obra_social))) pe.clinica_id, trim(pa.obra_social)
FROM paciente pa
JOIN persona pe ON pe.id = pa.id_persona
WHERE pa.id_obra_social IS NULL
  AND pe.clinica_id IS NOT NULL
  AND trim(COALESCE(pa.obra_social, '')) <> ''
  AND NOT EXISTS (
      SELECT 1 FROM obra_social os
      WHERE os.clinica_id = pe.clinica_id AND lower(os.nombre) = lower(trim(pa.obra_social))
  );

UPDATE paciente pa
SET id_obra_social = os.id
FROM persona pe, obra_social os
WHERE pe.id = pa.id_persona
  AND pa.id_obra_social IS NULL
  AND os.clinica_id = pe.clinica_id
  AND lower(os.nombre) = lower(trim(pa.obra_social));

ALTER TABLE obra_social ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON obra_social FROM anon, authenticated;
GRANT SELECT ON obra_social TO authenticated;

-- Lectura: el catálogo global para cualquier usuario; las altas propias, para el
-- staff y el auditor de esa clínica.
DROP POLICY IF EXISTS obra_social_select ON obra_social;
CREATE POLICY obra_social_select ON obra_social
    FOR SELECT TO authenticated
    USING (
        clinica_id IS NULL
        OR (
            clinica_id = public.app_current_clinica_id()
            AND (public.app_is_clinica_member() OR public.app_is_clinica_auditor())
        )
    );

-- Alcance del auditor por obra social del catálogo (reemplaza al texto libre de la
-- Fase J, que queda como respaldo para las membresías que no se pudieron migrar).
ALTER TABLE membresia ADD COLUMN IF NOT EXISTS alcance_id_obra_social bigint REFERENCES obra_social(id) ON DELETE SET NULL;
ALTER TABLE codigo_activacion ADD COLUMN IF NOT EXISTS alcance_id_obra_social bigint REFERENCES obra_social(id) ON DELETE SET NULL;

UPDATE membresia m
SET alcance_id_obra_social = os.id
FROM obra_social os
WHERE m.alcance_id_obra_social IS NULL
  AND m.alcance_obra_social IS NOT NULL
  AND (os.clinica_id IS NULL OR os.clinica_id = m.clinica_id)
  AND (lower(trim(m.alcance_obra_social)) = lower(os.nombre) OR lower(trim(m.alcance_obra_social)) = lower(os.sigla));

UPDATE codigo_activacion c
SET alcance_id_obra_social = os.id
FROM obra_social os
WHERE c.alcance_id_obra_social IS NULL
  AND c.alcance_obra_social IS NOT NULL
  AND (os.clinica_id IS NULL OR os.clinica_id = c.clinica_id)
  AND (lower(trim(c.alcance_obra_social)) = lower(os.nombre) OR lower(trim(c.alcance_obra_social)) = lower(os.sigla));

-- Helpers del alcance: por id de catálogo (preferido) o por texto (legado).
CREATE OR REPLACE FUNCTION public.app_auditor_alcance_id()
RETURNS bigint
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
    SELECT m.alcance_id_obra_social
    FROM membresia m
    JOIN persona pe ON pe.id = m.id_persona
    WHERE pe.id_auth = auth.uid()
      AND m.activo = true
      AND m.rol = 'auditor'
      AND m.clinica_id = public.app_current_clinica_id()
    LIMIT 1;
$$;
GRANT EXECUTE ON FUNCTION public.app_auditor_alcance_id() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.app_auditor_alcance_id() FROM anon, public;

-- ¿Auditor interno (sin alcance por obra social)?
CREATE OR REPLACE FUNCTION public.app_auditor_es_interno()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
    SELECT public.app_auditor_alcance_id() IS NULL AND public.app_auditor_alcance() IS NULL;
$$;
GRANT EXECUTE ON FUNCTION public.app_auditor_es_interno() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.app_auditor_es_interno() FROM anon, public;

CREATE OR REPLACE FUNCTION public.app_auditor_ve_paciente(p_id_paciente bigint)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
    SELECT CASE
        WHEN public.app_auditor_alcance_id() IS NOT NULL THEN EXISTS (
            SELECT 1 FROM paciente pa
            WHERE pa.id = p_id_paciente AND pa.id_obra_social = public.app_auditor_alcance_id()
        )
        WHEN public.app_auditor_alcance() IS NOT NULL THEN EXISTS (
            SELECT 1 FROM paciente pa
            WHERE pa.id = p_id_paciente AND lower(trim(pa.obra_social)) = public.app_auditor_alcance()
        )
        ELSE true
    END;
$$;
GRANT EXECUTE ON FUNCTION public.app_auditor_ve_paciente(bigint) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.app_auditor_ve_paciente(bigint) FROM anon, public;

CREATE OR REPLACE FUNCTION public.app_auditor_ve_persona(p_id_persona bigint)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
    SELECT CASE
        WHEN public.app_auditor_es_interno() THEN true
        WHEN NOT EXISTS (SELECT 1 FROM paciente pa WHERE pa.id_persona = p_id_persona) THEN true
        ELSE EXISTS (
            SELECT 1 FROM paciente pa
            WHERE pa.id_persona = p_id_persona AND public.app_auditor_ve_paciente(pa.id)
        )
    END;
$$;
GRANT EXECUTE ON FUNCTION public.app_auditor_ve_persona(bigint) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.app_auditor_ve_persona(bigint) FROM anon, public;

-- La bitácora usa "interno" (antes: alcance de texto IS NULL).
DROP POLICY IF EXISTS hc_acceso_select ON hc_acceso;
CREATE POLICY hc_acceso_select ON hc_acceso
    FOR SELECT TO authenticated
    USING (
        clinica_id = public.app_current_clinica_id()
        AND (
            public.app_is_clinica_admin()
            OR (
                public.app_is_clinica_auditor()
                AND (
                    public.app_auditor_es_interno()
                    OR (id_paciente IS NOT NULL AND public.app_auditor_ve_paciente(id_paciente))
                )
            )
        )
    );

-- ===========================================================================
-- B. CODIFICACIÓN: CIE-10 y prácticas
-- ===========================================================================

-- CIE-10: catálogo global de solo lectura. Subconjunto odontológico (K00–K14) más
-- algunos códigos generales de uso frecuente en la consulta odontológica.
CREATE TABLE IF NOT EXISTS cie10 (
    codigo      text PRIMARY KEY,
    descripcion text NOT NULL,
    categoria   boolean NOT NULL DEFAULT false   -- true = categoría de 3 caracteres
);

INSERT INTO cie10 (codigo, descripcion, categoria) VALUES
    ('K00', 'Trastornos del desarrollo y de la erupción de los dientes', true),
    ('K00.0', 'Anodoncia', false),
    ('K00.1', 'Dientes supernumerarios', false),
    ('K00.2', 'Anomalías del tamaño y de la forma del diente', false),
    ('K00.3', 'Dientes moteados', false),
    ('K00.4', 'Alteraciones en la formación dentaria', false),
    ('K00.5', 'Alteraciones hereditarias de la estructura dentaria, no clasificadas en otra parte', false),
    ('K00.6', 'Alteraciones en la erupción dentaria', false),
    ('K00.7', 'Síndrome de la erupción dentaria', false),
    ('K00.8', 'Otros trastornos del desarrollo de los dientes', false),
    ('K00.9', 'Trastorno del desarrollo de los dientes, no especificado', false),
    ('K01', 'Dientes incluidos e impactados', true),
    ('K01.0', 'Dientes incluidos', false),
    ('K01.1', 'Dientes impactados', false),
    ('K02', 'Caries dental', true),
    ('K02.0', 'Caries limitada al esmalte', false),
    ('K02.1', 'Caries de la dentina', false),
    ('K02.2', 'Caries del cemento', false),
    ('K02.3', 'Caries dentaria detenida', false),
    ('K02.4', 'Odontoclasia', false),
    ('K02.5', 'Caries con exposición pulpar', false),
    ('K02.8', 'Otras caries dentales', false),
    ('K02.9', 'Caries dental, no especificada', false),
    ('K03', 'Otras enfermedades de los tejidos duros de los dientes', true),
    ('K03.0', 'Atrición excesiva de los dientes', false),
    ('K03.1', 'Abrasión de los dientes', false),
    ('K03.2', 'Erosión de los dientes', false),
    ('K03.3', 'Reabsorción patológica de los dientes', false),
    ('K03.4', 'Hipercementosis', false),
    ('K03.5', 'Anquilosis dental', false),
    ('K03.6', 'Depósitos [acreciones] en los dientes', false),
    ('K03.7', 'Cambios posteruptivos del color de los tejidos dentales duros', false),
    ('K03.8', 'Otras enfermedades especificadas de los tejidos duros de los dientes', false),
    ('K03.9', 'Enfermedad no especificada de los tejidos duros de los dientes', false),
    ('K04', 'Enfermedades de la pulpa y de los tejidos periapicales', true),
    ('K04.0', 'Pulpitis', false),
    ('K04.1', 'Necrosis de la pulpa', false),
    ('K04.2', 'Degeneración de la pulpa', false),
    ('K04.3', 'Formación anormal de tejido duro en la pulpa', false),
    ('K04.4', 'Periodontitis apical aguda originada en la pulpa', false),
    ('K04.5', 'Periodontitis apical crónica', false),
    ('K04.6', 'Absceso periapical con fístula', false),
    ('K04.7', 'Absceso periapical sin fístula', false),
    ('K04.8', 'Quiste radicular', false),
    ('K04.9', 'Otras enfermedades y las no especificadas de la pulpa y del tejido periapical', false),
    ('K05', 'Gingivitis y enfermedades periodontales', true),
    ('K05.0', 'Gingivitis aguda', false),
    ('K05.1', 'Gingivitis crónica', false),
    ('K05.2', 'Periodontitis aguda', false),
    ('K05.3', 'Periodontitis crónica', false),
    ('K05.4', 'Periodontosis', false),
    ('K05.5', 'Otras enfermedades periodontales', false),
    ('K05.6', 'Enfermedad del periodonto, no especificada', false),
    ('K06', 'Otros trastornos de la encía y de la zona edéntula', true),
    ('K06.0', 'Retracción gingival', false),
    ('K06.1', 'Hiperplasia gingival', false),
    ('K06.2', 'Lesiones de la encía y de la zona edéntula asociadas con traumatismo', false),
    ('K06.8', 'Otros trastornos especificados de la encía y de la zona edéntula', false),
    ('K06.9', 'Trastorno no especificado de la encía y de la zona edéntula', false),
    ('K07', 'Anomalías dentofaciales [incluso la maloclusión]', true),
    ('K07.0', 'Anomalías evidentes del tamaño de los maxilares', false),
    ('K07.1', 'Anomalías de la relación maxilobasilar', false),
    ('K07.2', 'Anomalías de la relación entre los arcos dentarios', false),
    ('K07.3', 'Anomalías de la posición del diente', false),
    ('K07.4', 'Maloclusión de tipo no especificado', false),
    ('K07.5', 'Anomalías dentofaciales funcionales', false),
    ('K07.6', 'Trastornos de la articulación temporomaxilar', false),
    ('K07.8', 'Otras anomalías dentofaciales', false),
    ('K07.9', 'Anomalía dentofacial, no especificada', false),
    ('K08', 'Otros trastornos de los dientes y de sus estructuras de sostén', true),
    ('K08.0', 'Exfoliación de los dientes debida a causas sistémicas', false),
    ('K08.1', 'Pérdida de dientes debida a accidente, extracción o enfermedad periodontal local', false),
    ('K08.2', 'Atrofia del reborde alveolar desdentado', false),
    ('K08.3', 'Raíz dental retenida', false),
    ('K08.8', 'Otras afecciones especificadas de los dientes y de sus estructuras de sostén', false),
    ('K08.9', 'Trastorno de los dientes y de sus estructuras de sostén, no especificado', false),
    ('K09', 'Quistes de la región bucal, no clasificados en otra parte', true),
    ('K09.0', 'Quistes originados por el desarrollo de los dientes', false),
    ('K09.1', 'Quistes de las fisuras (no odontogénicos) de la región bucal', false),
    ('K09.2', 'Otros quistes de los maxilares', false),
    ('K09.8', 'Otros quistes de la región bucal, no clasificados en otra parte', false),
    ('K09.9', 'Quiste de la región bucal, sin otra especificación', false),
    ('K10', 'Otras enfermedades de los maxilares', true),
    ('K10.0', 'Trastornos del desarrollo de los maxilares', false),
    ('K10.1', 'Granuloma central de células gigantes', false),
    ('K10.2', 'Afecciones inflamatorias de los maxilares', false),
    ('K10.3', 'Alveolitis del maxilar', false),
    ('K10.8', 'Otras enfermedades especificadas de los maxilares', false),
    ('K10.9', 'Enfermedad de los maxilares, no especificada', false),
    ('K11', 'Enfermedades de las glándulas salivales', true),
    ('K11.0', 'Atrofia de glándula salival', false),
    ('K11.1', 'Hipertrofia de glándula salival', false),
    ('K11.2', 'Sialadenitis', false),
    ('K11.3', 'Absceso de glándula salival', false),
    ('K11.4', 'Fístula de glándula salival', false),
    ('K11.5', 'Sialolitiasis', false),
    ('K11.6', 'Mucocele de glándula salival', false),
    ('K11.7', 'Alteraciones de la secreción salival', false),
    ('K11.8', 'Otras enfermedades de las glándulas salivales', false),
    ('K11.9', 'Enfermedad de glándula salival, no especificada', false),
    ('K12', 'Estomatitis y lesiones afines', true),
    ('K12.0', 'Estomatitis aftosa recurrente', false),
    ('K12.1', 'Otras formas de estomatitis', false),
    ('K12.2', 'Celulitis y absceso de boca', false),
    ('K12.3', 'Mucositis oral (ulcerativa)', false),
    ('K13', 'Otras enfermedades de los labios y de la mucosa bucal', true),
    ('K13.0', 'Enfermedades de los labios', false),
    ('K13.1', 'Mordedura del labio y de la mejilla', false),
    ('K13.2', 'Leucoplasia y otras alteraciones del epitelio bucal, incluyendo la lengua', false),
    ('K13.3', 'Leucoplasia pilosa', false),
    ('K13.4', 'Granuloma y lesiones semejantes de la mucosa bucal', false),
    ('K13.5', 'Fibrosis de la submucosa bucal', false),
    ('K13.6', 'Hiperplasia irritativa de la mucosa bucal', false),
    ('K13.7', 'Otras lesiones y las no especificadas de la mucosa bucal', false),
    ('K14', 'Enfermedades de la lengua', true),
    ('K14.0', 'Glositis', false),
    ('K14.1', 'Lengua geográfica', false),
    ('K14.2', 'Glositis romboidea mediana', false),
    ('K14.3', 'Hipertrofia de las papilas linguales', false),
    ('K14.4', 'Atrofia de las papilas linguales', false),
    ('K14.5', 'Lengua plegada', false),
    ('K14.6', 'Glosodinia', false),
    ('K14.8', 'Otras enfermedades de la lengua', false),
    ('K14.9', 'Enfermedad de la lengua, no especificada', false),
    ('R19.6', 'Halitosis', false),
    ('S02.5', 'Fractura de los dientes', false),
    ('S03.2', 'Luxación de diente', false),
    ('Z00.0', 'Examen médico general', false),
    ('Z01.2', 'Examen odontológico', false),
    ('Z46.3', 'Prueba y ajuste de prótesis dental', false),
    ('Z46.4', 'Prueba y ajuste de dispositivo ortodóncico', false),
    ('Z97.2', 'Presencia de dispositivo protésico dental (completo o parcial)', false)
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE cie10 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON cie10 FROM anon, authenticated;
GRANT SELECT ON cie10 TO authenticated;
DROP POLICY IF EXISTS cie10_select ON cie10;
CREATE POLICY cie10_select ON cie10 FOR SELECT TO authenticated USING (true);

-- Prácticas: catálogo PROPIO de cada clínica (código + descripción). Se marca si
-- requiere autorización previa de la auditoría.
CREATE TABLE IF NOT EXISTS practica (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinica_id             uuid NOT NULL REFERENCES clinica(id) ON DELETE CASCADE,
    codigo                 text NOT NULL,
    descripcion            text NOT NULL,
    requiere_autorizacion  boolean NOT NULL DEFAULT false,
    activo                 boolean NOT NULL DEFAULT true,
    creado_en              timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS practica_codigo_uq ON practica (clinica_id, lower(codigo));

ALTER TABLE practica ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON practica FROM anon, authenticated;
GRANT SELECT ON practica TO authenticated;
DROP POLICY IF EXISTS practica_select ON practica;
CREATE POLICY practica_select ON practica
    FOR SELECT TO authenticated
    USING (
        clinica_id = public.app_current_clinica_id()
        AND (public.app_is_clinica_member() OR public.app_is_clinica_auditor())
    );

-- ===========================================================================
-- C. AUTORIZACIONES PREVIAS (antes que registro_practica, que la referencia)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS autorizacion (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinica_id           uuid   NOT NULL REFERENCES clinica(id) ON DELETE CASCADE,
    id_paciente          bigint NOT NULL REFERENCES paciente(id) ON DELETE CASCADE,
    id_profesional       bigint REFERENCES profesional(id) ON DELETE SET NULL,
    profesional_nombre   text,
    paciente_nombre      text,
    -- Práctica solicitada (snapshot del catálogo).
    id_practica          bigint REFERENCES practica(id) ON DELETE SET NULL,
    practica_codigo      text NOT NULL,
    practica_descripcion text NOT NULL,
    pieza                text,             -- diente/s o zona (texto libre)
    cantidad             int  NOT NULL DEFAULT 1 CHECK (cantidad BETWEEN 1 AND 99),
    diagnostico_cie10    text REFERENCES cie10(codigo),
    fundamento           text NOT NULL,
    odontograma          jsonb,            -- snapshot opcional del odontograma
    -- Cobertura al momento de pedirla (snapshot).
    id_obra_social       bigint REFERENCES obra_social(id) ON DELETE SET NULL,
    obra_social_nombre   text,
    nro_afiliado         text,
    -- Resolución de la auditoría.
    estado               text NOT NULL DEFAULT 'pendiente'
                         CHECK (estado IN ('pendiente', 'aprobada', 'rechazada', 'cancelada')),
    numero               text UNIQUE,      -- n.º de autorización (al aprobar)
    motivo               text,             -- respuesta/condiciones del auditor
    vence_en             date,
    id_persona_auditor   bigint REFERENCES persona(id) ON DELETE SET NULL,
    auditor_nombre       text,
    resuelta_en          timestamptz,
    creado_en            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_autorizacion_clinica_estado ON autorizacion (clinica_id, estado, creado_en DESC);
CREATE INDEX IF NOT EXISTS idx_autorizacion_paciente       ON autorizacion (id_paciente);
CREATE INDEX IF NOT EXISTS idx_autorizacion_profesional    ON autorizacion (id_profesional);

CREATE TABLE IF NOT EXISTS autorizacion_adjunto (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_autorizacion  bigint NOT NULL REFERENCES autorizacion(id) ON DELETE CASCADE,
    archivo_path     text   NOT NULL,      -- objeto en el bucket 'autorizaciones'
    archivo_mime     text,
    archivo_nombre   text,
    archivo_size     bigint,
    subido_en        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_autorizacion_adjunto ON autorizacion_adjunto (id_autorizacion);

ALTER TABLE autorizacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE autorizacion_adjunto ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON autorizacion, autorizacion_adjunto FROM anon, authenticated;
GRANT SELECT ON autorizacion, autorizacion_adjunto TO authenticated;

-- Lectura: staff operativo de la clínica o auditor (acotado a su alcance).
DROP POLICY IF EXISTS autorizacion_select ON autorizacion;
CREATE POLICY autorizacion_select ON autorizacion
    FOR SELECT TO authenticated
    USING (
        clinica_id = public.app_current_clinica_id()
        AND (
            public.app_is_clinica_member()
            OR (public.app_is_clinica_auditor() AND public.app_auditor_ve_paciente(id_paciente))
        )
    );

DROP POLICY IF EXISTS autorizacion_adjunto_select ON autorizacion_adjunto;
CREATE POLICY autorizacion_adjunto_select ON autorizacion_adjunto
    FOR SELECT TO authenticated
    USING (id_autorizacion IN (SELECT id FROM autorizacion)); -- hereda la RLS de autorizacion

-- Bucket privado de adjuntos (la app sube/baja por el backend con URLs firmadas).
INSERT INTO storage.buckets (id, name, public)
VALUES ('autorizaciones', 'autorizaciones', false)
ON CONFLICT (id) DO NOTHING;

-- Codificación por registro clínico (diagnósticos CIE-10 y prácticas realizadas).
CREATE TABLE IF NOT EXISTS registro_diagnostico (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_registro  uuid NOT NULL REFERENCES registro_clinico(id) ON DELETE CASCADE,
    codigo       text NOT NULL REFERENCES cie10(codigo),
    descripcion  text NOT NULL,           -- snapshot
    principal    boolean NOT NULL DEFAULT false,
    UNIQUE (id_registro, codigo)
);
CREATE INDEX IF NOT EXISTS idx_registro_diagnostico_codigo ON registro_diagnostico (codigo);

CREATE TABLE IF NOT EXISTS registro_practica (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_registro      uuid NOT NULL REFERENCES registro_clinico(id) ON DELETE CASCADE,
    id_practica      bigint REFERENCES practica(id) ON DELETE SET NULL,
    codigo           text NOT NULL,       -- snapshot
    descripcion      text NOT NULL,       -- snapshot
    pieza            text,
    cantidad         int  NOT NULL DEFAULT 1 CHECK (cantidad BETWEEN 1 AND 99),
    id_autorizacion  bigint REFERENCES autorizacion(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_registro_practica_registro ON registro_practica (id_registro);
CREATE INDEX IF NOT EXISTS idx_registro_practica_practica ON registro_practica (id_practica);

-- RLS igual que registro_diente (vía el registro padre): escritura admin/profesional;
-- lectura staff operativo + auditor acotado.
ALTER TABLE registro_diagnostico ENABLE ROW LEVEL SECURITY;
ALTER TABLE registro_practica ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON registro_diagnostico, registro_practica TO authenticated;
REVOKE ALL ON registro_diagnostico, registro_practica FROM anon;
GRANT USAGE, SELECT ON SEQUENCE registro_diagnostico_id_seq, registro_practica_id_seq TO authenticated;

DROP POLICY IF EXISTS registro_diagnostico_tenant ON registro_diagnostico;
CREATE POLICY registro_diagnostico_tenant ON registro_diagnostico
    FOR ALL TO authenticated
    USING (
        public.app_puede_escribir_hc()
        AND id_registro IN (SELECT id FROM registro_clinico WHERE clinica_id = public.app_current_clinica_id())
    )
    WITH CHECK (
        public.app_puede_escribir_hc()
        AND id_registro IN (SELECT id FROM registro_clinico WHERE clinica_id = public.app_current_clinica_id())
    );
DROP POLICY IF EXISTS registro_diagnostico_select ON registro_diagnostico;
CREATE POLICY registro_diagnostico_select ON registro_diagnostico
    FOR SELECT TO authenticated
    USING (id_registro IN (SELECT id FROM registro_clinico)); -- hereda la RLS de registro_clinico

DROP POLICY IF EXISTS registro_practica_tenant ON registro_practica;
CREATE POLICY registro_practica_tenant ON registro_practica
    FOR ALL TO authenticated
    USING (
        public.app_puede_escribir_hc()
        AND id_registro IN (SELECT id FROM registro_clinico WHERE clinica_id = public.app_current_clinica_id())
    )
    WITH CHECK (
        public.app_puede_escribir_hc()
        AND id_registro IN (SELECT id FROM registro_clinico WHERE clinica_id = public.app_current_clinica_id())
    );
DROP POLICY IF EXISTS registro_practica_select ON registro_practica;
CREATE POLICY registro_practica_select ON registro_practica
    FOR SELECT TO authenticated
    USING (id_registro IN (SELECT id FROM registro_clinico)); -- hereda la RLS de registro_clinico

-- ===========================================================================
-- D. ASISTENCIA A TURNOS + bitácora (acciones nuevas)
-- ===========================================================================
ALTER TABLE turno DROP CONSTRAINT IF EXISTS turno_estado_check;
ALTER TABLE turno ADD CONSTRAINT turno_estado_check
    CHECK (estado IN ('reservado', 'cancelado', 'atendido', 'ausente'));

-- La asistencia la marca solo el staff (backend). El paciente puede actualizar su
-- turno por la RLS de la Fase 3 (cancelar): no debe poder marcarse "atendido".
CREATE OR REPLACE FUNCTION public.turno_proteger_asistencia()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
    IF COALESCE(auth.jwt()->>'role', 'service_role') = 'service_role' THEN
        RETURN NEW;
    END IF;
    IF NEW.estado IN ('atendido', 'ausente')
       AND NEW.estado IS DISTINCT FROM (CASE WHEN TG_OP = 'UPDATE' THEN OLD.estado END) THEN
        RAISE EXCEPTION 'La asistencia solo la registra la clínica';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS turno_asistencia_protegida ON turno;
CREATE TRIGGER turno_asistencia_protegida
    BEFORE INSERT OR UPDATE ON turno
    FOR EACH ROW EXECUTE FUNCTION public.turno_proteger_asistencia();

ALTER TABLE hc_acceso DROP CONSTRAINT IF EXISTS hc_acceso_accion_check;
ALTER TABLE hc_acceso ADD CONSTRAINT hc_acceso_accion_check CHECK (accion IN (
    'ver_hc', 'crear_registro', 'registrar_paciente',
    'exportar_hc', 'importar_hc',
    'ver_registro_auditoria', 'revisar', 'responder',
    'solicitar_autorizacion', 'ver_autorizacion', 'resolver_autorizacion',
    'ver_adjunto_autorizacion', 'editar_cobertura'));
